//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ERP.Web.Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<V_S_Log> V_S_Log
        {
            get
            {
                if ((_V_S_Log == null))
                {
                    _V_S_Log = base.CreateObjectSet<V_S_Log>("V_S_Log");
                }
                return _V_S_Log;
            }
        }
        private ObjectSet<V_S_Log> _V_S_Log;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<V_S_DataBase> V_S_DataBase
        {
            get
            {
                if ((_V_S_DataBase == null))
                {
                    _V_S_DataBase = base.CreateObjectSet<V_S_DataBase>("V_S_DataBase");
                }
                return _V_S_DataBase;
            }
        }
        private ObjectSet<V_S_DataBase> _V_S_DataBase;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<V_S_Function> V_S_Function
        {
            get
            {
                if ((_V_S_Function == null))
                {
                    _V_S_Function = base.CreateObjectSet<V_S_Function>("V_S_Function");
                }
                return _V_S_Function;
            }
        }
        private ObjectSet<V_S_Function> _V_S_Function;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<V_S_User_GroupDataBase> V_S_User_GroupDataBase
        {
            get
            {
                if ((_V_S_User_GroupDataBase == null))
                {
                    _V_S_User_GroupDataBase = base.CreateObjectSet<V_S_User_GroupDataBase>("V_S_User_GroupDataBase");
                }
                return _V_S_User_GroupDataBase;
            }
        }
        private ObjectSet<V_S_User_GroupDataBase> _V_S_User_GroupDataBase;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<V_S_User> V_S_User
        {
            get
            {
                if ((_V_S_User == null))
                {
                    _V_S_User = base.CreateObjectSet<V_S_User>("V_S_User");
                }
                return _V_S_User;
            }
        }
        private ObjectSet<V_S_User> _V_S_User;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<V_S_UserGroup> V_S_UserGroup
        {
            get
            {
                if ((_V_S_UserGroup == null))
                {
                    _V_S_UserGroup = base.CreateObjectSet<V_S_UserGroup>("V_S_UserGroup");
                }
                return _V_S_UserGroup;
            }
        }
        private ObjectSet<V_S_UserGroup> _V_S_UserGroup;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<V_U_ProcessClass> V_U_ProcessClass
        {
            get
            {
                if ((_V_U_ProcessClass == null))
                {
                    _V_U_ProcessClass = base.CreateObjectSet<V_U_ProcessClass>("V_U_ProcessClass");
                }
                return _V_U_ProcessClass;
            }
        }
        private ObjectSet<V_U_ProcessClass> _V_U_ProcessClass;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the V_S_Log EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToV_S_Log(V_S_Log v_S_Log)
        {
            base.AddObject("V_S_Log", v_S_Log);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the V_S_DataBase EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToV_S_DataBase(V_S_DataBase v_S_DataBase)
        {
            base.AddObject("V_S_DataBase", v_S_DataBase);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the V_S_Function EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToV_S_Function(V_S_Function v_S_Function)
        {
            base.AddObject("V_S_Function", v_S_Function);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the V_S_User_GroupDataBase EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToV_S_User_GroupDataBase(V_S_User_GroupDataBase v_S_User_GroupDataBase)
        {
            base.AddObject("V_S_User_GroupDataBase", v_S_User_GroupDataBase);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the V_S_User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToV_S_User(V_S_User v_S_User)
        {
            base.AddObject("V_S_User", v_S_User);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the V_S_UserGroup EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToV_S_UserGroup(V_S_UserGroup v_S_UserGroup)
        {
            base.AddObject("V_S_UserGroup", v_S_UserGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the V_U_ProcessClass EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToV_U_ProcessClass(V_U_ProcessClass v_U_ProcessClass)
        {
            base.AddObject("V_U_ProcessClass", v_U_ProcessClass);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ERPModel", Name="V_S_DataBase")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class V_S_DataBase : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new V_S_DataBase object.
        /// </summary>
        /// <param name="dBCode">Initial value of the DBCode property.</param>
        public static V_S_DataBase CreateV_S_DataBase(global::System.String dBCode)
        {
            V_S_DataBase v_S_DataBase = new V_S_DataBase();
            v_S_DataBase.DBCode = dBCode;
            return v_S_DataBase;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DBCode
        {
            get
            {
                return _DBCode;
            }
            set
            {
                if (_DBCode != value)
                {
                    OnDBCodeChanging(value);
                    ReportPropertyChanging("DBCode");
                    _DBCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("DBCode");
                    OnDBCodeChanged();
                }
            }
        }
        private global::System.String _DBCode;
        partial void OnDBCodeChanging(global::System.String value);
        partial void OnDBCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DBName
        {
            get
            {
                return _DBName;
            }
            set
            {
                OnDBNameChanging(value);
                ReportPropertyChanging("DBName");
                _DBName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DBName");
                OnDBNameChanged();
            }
        }
        private global::System.String _DBName;
        partial void OnDBNameChanging(global::System.String value);
        partial void OnDBNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ERPModel", Name="V_S_Function")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class V_S_Function : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new V_S_Function object.
        /// </summary>
        /// <param name="funID">Initial value of the FunID property.</param>
        public static V_S_Function CreateV_S_Function(global::System.String funID)
        {
            V_S_Function v_S_Function = new V_S_Function();
            v_S_Function.FunID = funID;
            return v_S_Function;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FunID
        {
            get
            {
                return _FunID;
            }
            set
            {
                if (_FunID != value)
                {
                    OnFunIDChanging(value);
                    ReportPropertyChanging("FunID");
                    _FunID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FunID");
                    OnFunIDChanged();
                }
            }
        }
        private global::System.String _FunID;
        partial void OnFunIDChanging(global::System.String value);
        partial void OnFunIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FunPID
        {
            get
            {
                return _FunPID;
            }
            set
            {
                OnFunPIDChanging(value);
                ReportPropertyChanging("FunPID");
                _FunPID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FunPID");
                OnFunPIDChanged();
            }
        }
        private global::System.String _FunPID;
        partial void OnFunPIDChanging(global::System.String value);
        partial void OnFunPIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FunCode
        {
            get
            {
                return _FunCode;
            }
            set
            {
                OnFunCodeChanging(value);
                ReportPropertyChanging("FunCode");
                _FunCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FunCode");
                OnFunCodeChanged();
            }
        }
        private global::System.String _FunCode;
        partial void OnFunCodeChanging(global::System.String value);
        partial void OnFunCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FunName
        {
            get
            {
                return _FunName;
            }
            set
            {
                OnFunNameChanging(value);
                ReportPropertyChanging("FunName");
                _FunName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FunName");
                OnFunNameChanged();
            }
        }
        private global::System.String _FunName;
        partial void OnFunNameChanging(global::System.String value);
        partial void OnFunNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FunRight
        {
            get
            {
                return _FunRight;
            }
            set
            {
                OnFunRightChanging(value);
                ReportPropertyChanging("FunRight");
                _FunRight = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FunRight");
                OnFunRightChanged();
            }
        }
        private global::System.String _FunRight;
        partial void OnFunRightChanging(global::System.String value);
        partial void OnFunRightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> F_ShowInMenu
        {
            get
            {
                return _F_ShowInMenu;
            }
            set
            {
                OnF_ShowInMenuChanging(value);
                ReportPropertyChanging("F_ShowInMenu");
                _F_ShowInMenu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("F_ShowInMenu");
                OnF_ShowInMenuChanged();
            }
        }
        private Nullable<global::System.Boolean> _F_ShowInMenu;
        partial void OnF_ShowInMenuChanging(Nullable<global::System.Boolean> value);
        partial void OnF_ShowInMenuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> F_Open
        {
            get
            {
                return _F_Open;
            }
            set
            {
                OnF_OpenChanging(value);
                ReportPropertyChanging("F_Open");
                _F_Open = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("F_Open");
                OnF_OpenChanged();
            }
        }
        private Nullable<global::System.Boolean> _F_Open;
        partial void OnF_OpenChanging(Nullable<global::System.Boolean> value);
        partial void OnF_OpenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageURL
        {
            get
            {
                return _ImageURL;
            }
            set
            {
                OnImageURLChanging(value);
                ReportPropertyChanging("ImageURL");
                _ImageURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageURL");
                OnImageURLChanged();
            }
        }
        private global::System.String _ImageURL;
        partial void OnImageURLChanging(global::System.String value);
        partial void OnImageURLChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ERPModel", Name="V_S_Log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class V_S_Log : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new V_S_Log object.
        /// </summary>
        /// <param name="logTime">Initial value of the LogTime property.</param>
        /// <param name="funCode">Initial value of the FunCode property.</param>
        public static V_S_Log CreateV_S_Log(global::System.DateTime logTime, global::System.String funCode)
        {
            V_S_Log v_S_Log = new V_S_Log();
            v_S_Log.LogTime = logTime;
            v_S_Log.FunCode = funCode;
            return v_S_Log;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LogTime
        {
            get
            {
                return _LogTime;
            }
            set
            {
                if (_LogTime != value)
                {
                    OnLogTimeChanging(value);
                    ReportPropertyChanging("LogTime");
                    _LogTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LogTime");
                    OnLogTimeChanged();
                }
            }
        }
        private global::System.DateTime _LogTime;
        partial void OnLogTimeChanging(global::System.DateTime value);
        partial void OnLogTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LogTimeSmall
        {
            get
            {
                return _LogTimeSmall;
            }
            set
            {
                OnLogTimeSmallChanging(value);
                ReportPropertyChanging("LogTimeSmall");
                _LogTimeSmall = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LogTimeSmall");
                OnLogTimeSmallChanged();
            }
        }
        private global::System.String _LogTimeSmall;
        partial void OnLogTimeSmallChanging(global::System.String value);
        partial void OnLogTimeSmallChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserCode
        {
            get
            {
                return _UserCode;
            }
            set
            {
                OnUserCodeChanging(value);
                ReportPropertyChanging("UserCode");
                _UserCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserCode");
                OnUserCodeChanged();
            }
        }
        private global::System.String _UserCode;
        partial void OnUserCodeChanging(global::System.String value);
        partial void OnUserCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DBCode
        {
            get
            {
                return _DBCode;
            }
            set
            {
                OnDBCodeChanging(value);
                ReportPropertyChanging("DBCode");
                _DBCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DBCode");
                OnDBCodeChanged();
            }
        }
        private global::System.String _DBCode;
        partial void OnDBCodeChanging(global::System.String value);
        partial void OnDBCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FunCode
        {
            get
            {
                return _FunCode;
            }
            set
            {
                if (_FunCode != value)
                {
                    OnFunCodeChanging(value);
                    ReportPropertyChanging("FunCode");
                    _FunCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FunCode");
                    OnFunCodeChanged();
                }
            }
        }
        private global::System.String _FunCode;
        partial void OnFunCodeChanging(global::System.String value);
        partial void OnFunCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientID
        {
            get
            {
                return _ClientID;
            }
            set
            {
                OnClientIDChanging(value);
                ReportPropertyChanging("ClientID");
                _ClientID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientID");
                OnClientIDChanged();
            }
        }
        private global::System.String _ClientID;
        partial void OnClientIDChanging(global::System.String value);
        partial void OnClientIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DBName
        {
            get
            {
                return _DBName;
            }
            set
            {
                OnDBNameChanging(value);
                ReportPropertyChanging("DBName");
                _DBName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DBName");
                OnDBNameChanged();
            }
        }
        private global::System.String _DBName;
        partial void OnDBNameChanging(global::System.String value);
        partial void OnDBNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FunName
        {
            get
            {
                return _FunName;
            }
            set
            {
                OnFunNameChanging(value);
                ReportPropertyChanging("FunName");
                _FunName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FunName");
                OnFunNameChanged();
            }
        }
        private global::System.String _FunName;
        partial void OnFunNameChanging(global::System.String value);
        partial void OnFunNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ERPModel", Name="V_S_User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class V_S_User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new V_S_User object.
        /// </summary>
        /// <param name="userCode">Initial value of the UserCode property.</param>
        public static V_S_User CreateV_S_User(global::System.String userCode)
        {
            V_S_User v_S_User = new V_S_User();
            v_S_User.UserCode = userCode;
            return v_S_User;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserCode
        {
            get
            {
                return _UserCode;
            }
            set
            {
                if (_UserCode != value)
                {
                    OnUserCodeChanging(value);
                    ReportPropertyChanging("UserCode");
                    _UserCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserCode");
                    OnUserCodeChanged();
                }
            }
        }
        private global::System.String _UserCode;
        partial void OnUserCodeChanging(global::System.String value);
        partial void OnUserCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserExplain
        {
            get
            {
                return _UserExplain;
            }
            set
            {
                OnUserExplainChanging(value);
                ReportPropertyChanging("UserExplain");
                _UserExplain = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserExplain");
                OnUserExplainChanged();
            }
        }
        private global::System.String _UserExplain;
        partial void OnUserExplainChanging(global::System.String value);
        partial void OnUserExplainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserPassword
        {
            get
            {
                return _UserPassword;
            }
            set
            {
                OnUserPasswordChanging(value);
                ReportPropertyChanging("UserPassword");
                _UserPassword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserPassword");
                OnUserPasswordChanged();
            }
        }
        private global::System.String _UserPassword;
        partial void OnUserPasswordChanging(global::System.String value);
        partial void OnUserPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserRight
        {
            get
            {
                return _UserRight;
            }
            set
            {
                OnUserRightChanging(value);
                ReportPropertyChanging("UserRight");
                _UserRight = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserRight");
                OnUserRightChanged();
            }
        }
        private global::System.String _UserRight;
        partial void OnUserRightChanging(global::System.String value);
        partial void OnUserRightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> MakeDate
        {
            get
            {
                return _MakeDate;
            }
            set
            {
                OnMakeDateChanging(value);
                ReportPropertyChanging("MakeDate");
                _MakeDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MakeDate");
                OnMakeDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _MakeDate;
        partial void OnMakeDateChanging(Nullable<global::System.DateTime> value);
        partial void OnMakeDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> F_Admin
        {
            get
            {
                return _F_Admin;
            }
            set
            {
                OnF_AdminChanging(value);
                ReportPropertyChanging("F_Admin");
                _F_Admin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("F_Admin");
                OnF_AdminChanged();
            }
        }
        private Nullable<global::System.Boolean> _F_Admin;
        partial void OnF_AdminChanging(Nullable<global::System.Boolean> value);
        partial void OnF_AdminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> F_Super
        {
            get
            {
                return _F_Super;
            }
            set
            {
                OnF_SuperChanging(value);
                ReportPropertyChanging("F_Super");
                _F_Super = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("F_Super");
                OnF_SuperChanged();
            }
        }
        private Nullable<global::System.Boolean> _F_Super;
        partial void OnF_SuperChanging(Nullable<global::System.Boolean> value);
        partial void OnF_SuperChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> F_Stop
        {
            get
            {
                return _F_Stop;
            }
            set
            {
                OnF_StopChanging(value);
                ReportPropertyChanging("F_Stop");
                _F_Stop = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("F_Stop");
                OnF_StopChanged();
            }
        }
        private Nullable<global::System.Boolean> _F_Stop;
        partial void OnF_StopChanging(Nullable<global::System.Boolean> value);
        partial void OnF_StopChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLoginDate
        {
            get
            {
                return _LastLoginDate;
            }
            set
            {
                OnLastLoginDateChanging(value);
                ReportPropertyChanging("LastLoginDate");
                _LastLoginDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLoginDate");
                OnLastLoginDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLoginDate;
        partial void OnLastLoginDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoginDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LoginDate
        {
            get
            {
                return _LoginDate;
            }
            set
            {
                OnLoginDateChanging(value);
                ReportPropertyChanging("LoginDate");
                _LoginDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoginDate");
                OnLoginDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LoginDate;
        partial void OnLoginDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLoginDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserImage
        {
            get
            {
                return _UserImage;
            }
            set
            {
                OnUserImageChanging(value);
                ReportPropertyChanging("UserImage");
                _UserImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserImage");
                OnUserImageChanged();
            }
        }
        private global::System.String _UserImage;
        partial void OnUserImageChanging(global::System.String value);
        partial void OnUserImageChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ERPModel", Name="V_S_User_GroupDataBase")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class V_S_User_GroupDataBase : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new V_S_User_GroupDataBase object.
        /// </summary>
        /// <param name="userCode">Initial value of the UserCode property.</param>
        /// <param name="gpID">Initial value of the GpID property.</param>
        /// <param name="subID">Initial value of the SubID property.</param>
        public static V_S_User_GroupDataBase CreateV_S_User_GroupDataBase(global::System.String userCode, global::System.Int32 gpID, global::System.Int32 subID)
        {
            V_S_User_GroupDataBase v_S_User_GroupDataBase = new V_S_User_GroupDataBase();
            v_S_User_GroupDataBase.UserCode = userCode;
            v_S_User_GroupDataBase.GpID = gpID;
            v_S_User_GroupDataBase.SubID = subID;
            return v_S_User_GroupDataBase;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserCode
        {
            get
            {
                return _UserCode;
            }
            set
            {
                if (_UserCode != value)
                {
                    OnUserCodeChanging(value);
                    ReportPropertyChanging("UserCode");
                    _UserCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserCode");
                    OnUserCodeChanged();
                }
            }
        }
        private global::System.String _UserCode;
        partial void OnUserCodeChanging(global::System.String value);
        partial void OnUserCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GpCode
        {
            get
            {
                return _GpCode;
            }
            set
            {
                OnGpCodeChanging(value);
                ReportPropertyChanging("GpCode");
                _GpCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GpCode");
                OnGpCodeChanged();
            }
        }
        private global::System.String _GpCode;
        partial void OnGpCodeChanging(global::System.String value);
        partial void OnGpCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GpName
        {
            get
            {
                return _GpName;
            }
            set
            {
                OnGpNameChanging(value);
                ReportPropertyChanging("GpName");
                _GpName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GpName");
                OnGpNameChanged();
            }
        }
        private global::System.String _GpName;
        partial void OnGpNameChanging(global::System.String value);
        partial void OnGpNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GpID
        {
            get
            {
                return _GpID;
            }
            set
            {
                if (_GpID != value)
                {
                    OnGpIDChanging(value);
                    ReportPropertyChanging("GpID");
                    _GpID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GpID");
                    OnGpIDChanged();
                }
            }
        }
        private global::System.Int32 _GpID;
        partial void OnGpIDChanging(global::System.Int32 value);
        partial void OnGpIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> F_RBCusCode
        {
            get
            {
                return _F_RBCusCode;
            }
            set
            {
                OnF_RBCusCodeChanging(value);
                ReportPropertyChanging("F_RBCusCode");
                _F_RBCusCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("F_RBCusCode");
                OnF_RBCusCodeChanged();
            }
        }
        private Nullable<global::System.Boolean> _F_RBCusCode;
        partial void OnF_RBCusCodeChanging(Nullable<global::System.Boolean> value);
        partial void OnF_RBCusCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> F_RBWhCode
        {
            get
            {
                return _F_RBWhCode;
            }
            set
            {
                OnF_RBWhCodeChanging(value);
                ReportPropertyChanging("F_RBWhCode");
                _F_RBWhCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("F_RBWhCode");
                OnF_RBWhCodeChanged();
            }
        }
        private Nullable<global::System.Boolean> _F_RBWhCode;
        partial void OnF_RBWhCodeChanging(Nullable<global::System.Boolean> value);
        partial void OnF_RBWhCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> F_RUWhCode
        {
            get
            {
                return _F_RUWhCode;
            }
            set
            {
                OnF_RUWhCodeChanging(value);
                ReportPropertyChanging("F_RUWhCode");
                _F_RUWhCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("F_RUWhCode");
                OnF_RUWhCodeChanged();
            }
        }
        private Nullable<global::System.Boolean> _F_RUWhCode;
        partial void OnF_RUWhCodeChanging(Nullable<global::System.Boolean> value);
        partial void OnF_RUWhCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DBCode
        {
            get
            {
                return _DBCode;
            }
            set
            {
                OnDBCodeChanging(value);
                ReportPropertyChanging("DBCode");
                _DBCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DBCode");
                OnDBCodeChanged();
            }
        }
        private global::System.String _DBCode;
        partial void OnDBCodeChanging(global::System.String value);
        partial void OnDBCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DBName
        {
            get
            {
                return _DBName;
            }
            set
            {
                OnDBNameChanging(value);
                ReportPropertyChanging("DBName");
                _DBName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DBName");
                OnDBNameChanged();
            }
        }
        private global::System.String _DBName;
        partial void OnDBNameChanging(global::System.String value);
        partial void OnDBNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SubID
        {
            get
            {
                return _SubID;
            }
            set
            {
                if (_SubID != value)
                {
                    OnSubIDChanging(value);
                    ReportPropertyChanging("SubID");
                    _SubID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SubID");
                    OnSubIDChanged();
                }
            }
        }
        private global::System.Int32 _SubID;
        partial void OnSubIDChanging(global::System.Int32 value);
        partial void OnSubIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ERPModel", Name="V_S_UserGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class V_S_UserGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new V_S_UserGroup object.
        /// </summary>
        /// <param name="gpCode">Initial value of the GpCode property.</param>
        /// <param name="gpID">Initial value of the GpID property.</param>
        public static V_S_UserGroup CreateV_S_UserGroup(global::System.String gpCode, global::System.Int32 gpID)
        {
            V_S_UserGroup v_S_UserGroup = new V_S_UserGroup();
            v_S_UserGroup.GpCode = gpCode;
            v_S_UserGroup.GpID = gpID;
            return v_S_UserGroup;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GpCode
        {
            get
            {
                return _GpCode;
            }
            set
            {
                if (_GpCode != value)
                {
                    OnGpCodeChanging(value);
                    ReportPropertyChanging("GpCode");
                    _GpCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("GpCode");
                    OnGpCodeChanged();
                }
            }
        }
        private global::System.String _GpCode;
        partial void OnGpCodeChanging(global::System.String value);
        partial void OnGpCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GpName
        {
            get
            {
                return _GpName;
            }
            set
            {
                OnGpNameChanging(value);
                ReportPropertyChanging("GpName");
                _GpName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GpName");
                OnGpNameChanged();
            }
        }
        private global::System.String _GpName;
        partial void OnGpNameChanging(global::System.String value);
        partial void OnGpNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GpExplain
        {
            get
            {
                return _GpExplain;
            }
            set
            {
                OnGpExplainChanging(value);
                ReportPropertyChanging("GpExplain");
                _GpExplain = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GpExplain");
                OnGpExplainChanged();
            }
        }
        private global::System.String _GpExplain;
        partial void OnGpExplainChanging(global::System.String value);
        partial void OnGpExplainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GpID
        {
            get
            {
                return _GpID;
            }
            set
            {
                if (_GpID != value)
                {
                    OnGpIDChanging(value);
                    ReportPropertyChanging("GpID");
                    _GpID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GpID");
                    OnGpIDChanged();
                }
            }
        }
        private global::System.Int32 _GpID;
        partial void OnGpIDChanging(global::System.Int32 value);
        partial void OnGpIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DBCode
        {
            get
            {
                return _DBCode;
            }
            set
            {
                OnDBCodeChanging(value);
                ReportPropertyChanging("DBCode");
                _DBCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DBCode");
                OnDBCodeChanged();
            }
        }
        private global::System.String _DBCode;
        partial void OnDBCodeChanging(global::System.String value);
        partial void OnDBCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> F_RBCusCode
        {
            get
            {
                return _F_RBCusCode;
            }
            set
            {
                OnF_RBCusCodeChanging(value);
                ReportPropertyChanging("F_RBCusCode");
                _F_RBCusCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("F_RBCusCode");
                OnF_RBCusCodeChanged();
            }
        }
        private Nullable<global::System.Boolean> _F_RBCusCode;
        partial void OnF_RBCusCodeChanging(Nullable<global::System.Boolean> value);
        partial void OnF_RBCusCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> F_RBWhCode
        {
            get
            {
                return _F_RBWhCode;
            }
            set
            {
                OnF_RBWhCodeChanging(value);
                ReportPropertyChanging("F_RBWhCode");
                _F_RBWhCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("F_RBWhCode");
                OnF_RBWhCodeChanged();
            }
        }
        private Nullable<global::System.Boolean> _F_RBWhCode;
        partial void OnF_RBWhCodeChanging(Nullable<global::System.Boolean> value);
        partial void OnF_RBWhCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> F_RUWhCode
        {
            get
            {
                return _F_RUWhCode;
            }
            set
            {
                OnF_RUWhCodeChanging(value);
                ReportPropertyChanging("F_RUWhCode");
                _F_RUWhCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("F_RUWhCode");
                OnF_RUWhCodeChanged();
            }
        }
        private Nullable<global::System.Boolean> _F_RUWhCode;
        partial void OnF_RUWhCodeChanging(Nullable<global::System.Boolean> value);
        partial void OnF_RUWhCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> F_RBDpCode
        {
            get
            {
                return _F_RBDpCode;
            }
            set
            {
                OnF_RBDpCodeChanging(value);
                ReportPropertyChanging("F_RBDpCode");
                _F_RBDpCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("F_RBDpCode");
                OnF_RBDpCodeChanged();
            }
        }
        private Nullable<global::System.Boolean> _F_RBDpCode;
        partial void OnF_RBDpCodeChanging(Nullable<global::System.Boolean> value);
        partial void OnF_RBDpCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> F_RBSpCode
        {
            get
            {
                return _F_RBSpCode;
            }
            set
            {
                OnF_RBSpCodeChanging(value);
                ReportPropertyChanging("F_RBSpCode");
                _F_RBSpCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("F_RBSpCode");
                OnF_RBSpCodeChanged();
            }
        }
        private Nullable<global::System.Boolean> _F_RBSpCode;
        partial void OnF_RBSpCodeChanging(Nullable<global::System.Boolean> value);
        partial void OnF_RBSpCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DBName
        {
            get
            {
                return _DBName;
            }
            set
            {
                OnDBNameChanging(value);
                ReportPropertyChanging("DBName");
                _DBName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DBName");
                OnDBNameChanged();
            }
        }
        private global::System.String _DBName;
        partial void OnDBNameChanging(global::System.String value);
        partial void OnDBNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ERPModel", Name="V_U_ProcessClass")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class V_U_ProcessClass : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new V_U_ProcessClass object.
        /// </summary>
        /// <param name="keyCode">Initial value of the KeyCode property.</param>
        public static V_U_ProcessClass CreateV_U_ProcessClass(global::System.String keyCode)
        {
            V_U_ProcessClass v_U_ProcessClass = new V_U_ProcessClass();
            v_U_ProcessClass.KeyCode = keyCode;
            return v_U_ProcessClass;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String KeyCode
        {
            get
            {
                return _KeyCode;
            }
            set
            {
                if (_KeyCode != value)
                {
                    OnKeyCodeChanging(value);
                    ReportPropertyChanging("KeyCode");
                    _KeyCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("KeyCode");
                    OnKeyCodeChanged();
                }
            }
        }
        private global::System.String _KeyCode;
        partial void OnKeyCodeChanging(global::System.String value);
        partial void OnKeyCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KeyName
        {
            get
            {
                return _KeyName;
            }
            set
            {
                OnKeyNameChanging(value);
                ReportPropertyChanging("KeyName");
                _KeyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KeyName");
                OnKeyNameChanged();
            }
        }
        private global::System.String _KeyName;
        partial void OnKeyNameChanging(global::System.String value);
        partial void OnKeyNameChanged();

        #endregion

    
    }

    #endregion

    
}
